#!/usr/bin/python

"""Prints the given UNIX epoch timestamp as an ISO local date.

Usage: epoch timestamp

"""

from datetime import datetime
import argparse


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("timestamp")
    args = parser.parse_args()

    print(datetime.fromtimestamp(int(args.timestamp)).isoformat())


if __name__ == '__main__':
    main()
